-- This loads the data into MySQL
-- You need to set up my.cinf with
-- [mysqld]
-- secure-file-priv=/usr/local/share/data
-- innodb_lock_wait_timeout=100000

-- Also for the directory of item and result files I used
-- cat * | grep -v testid | sort -n > test_item_2021.csv
-- Or equivalent, Sorting makes it load faster and be more
-- optimised for reads
-- Had to change LATERAL to LAT too as LATERAL is an SQL keyword


DROP DATABASE IF EXISTS MOT;

CREATE DATABASE MOT;

use MOT;

CREATE TABLE TESTRESULT (
	TESTID INT UNSIGNED
	,VEHICLEID INT UNSIGNED
	,TESTDATE DATE
	,TESTCLASSID CHAR(2)
	,TESTTYPE CHAR(2)
	,TESTRESULT CHAR(5)
	,TESTMILEAGE INT UNSIGNED
	,POSTCODEREGION CHAR(2)
	,MAKE CHAR(50)
	,MODEL CHAR(50)
	,COLOUR CHAR(16)
	,FUELTYPE CHAR(2)
	,CYLCPCTY INT UNSIGNED
	,FIRSTUSEDATE DATE
	,PRIMARY KEY (TESTID)
	,INDEX IDX1 (TESTDATE, TESTTYPE, TESTRESULT, TESTCLASSID)
	)
;

CREATE TABLE TESTITEM (
	TESTID INT UNSIGNED
	,RFRID SMALLINT UNSIGNED
	,RFRTYPE CHAR(1)
	,LOCATIONID INT
	,DMARK CHAR(1)
	,PRIMARY KEY(TESTID,RFRID,LOCATIONID)
	,INDEX IDX1 (RFRID)
	);

	CREATE TABLE TESTITEM_DETAIL (
	RFRID SMALLINT UNSIGNED
	,TESTCLASSID CHAR(2)
	,TSTITMID SMALLINT UNSIGNED
	,MINORITEM CHAR(1)
	,RFRDESC CHAR(250)
	,RFRLOCMARKER CHAR(1)
	,RFRINSPMANDESC TEXT
	,RFRADVISORYTEXT CHAR(250)
	,TSTITMSETSECID SMALLINT UNSIGNED
	,PRIMARY KEY (RFRID, TESTCLASSID)
	,INDEX IDX1 (TSTITMID, TESTCLASSID)
	,INDEX IDX2 (TSTITMSETSECID, TESTCLASSID)
	)
;

CREATE TABLE TESTITEM_GROUP (
	TSTITMID SMALLINT UNSIGNED
	,TESTCLASSID CHAR(2)
	,PARENTID SMALLINT UNSIGNED
	,TSTITMSETSECID SMALLINT UNSIGNED
	,ITEMNAME CHAR(100)
	,PRIMARY KEY (TSTITMID, TESTCLASSID)
	,INDEX IDX1 (PARENTID, TESTCLASSID)
	,INDEX IDX2(TSTITMSETSECID, TESTCLASSID)
	)
;

CREATE TABLE FAILURE_LOCATION (
	FAILURELOCATIONID INT(4)
	,LAT CHAR(20)
	,LONGITUDINAL CHAR(20)
	,VERTICAL CHAR(20)
	,PRIMARY KEY (FAILURELOCATIONID)
	)
;


CREATE TABLE TEST_OUTCOME (
  RESULTCODE CHAR(6),
  RESULT CHAR(40),
  PRIMARY KEY (RESULTCODE)
);

CREATE TABLE TEST_TYPES (
  TYPECODE CHAR(6),
  TESTTYPE CHAR(40),
  PRIMARY KEY (TYPECODE)
);

CREATE TABLE FUEL_TYPES (
  TYPECODE CHAR(6),
  FUEL_TYPE CHAR(40),
  PRIMARY KEY (TYPECODE)
);



LOAD DATA  LOCAL INFILE 'test_result_2021.csv' IGNORE
INTO TABLE TESTRESULT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
;


LOAD DATA LOCAL INFILE 'test_item_2021.csv' IGNORE
INTO TABLE TESTITEM
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
;

LOAD DATA LOCAL INFILE 'dft_item_detail.csv' IGNORE
INTO TABLE TESTITEM_DETAIL
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;

LOAD DATA  LOCAL INFILE 'dft_group_detail.csv' IGNORE
INTO TABLE TESTITEM_GROUP
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;



LOAD DATA  LOCAL INFILE 'dft_mdr_rfr_location.csv' IGNORE
INTO TABLE FAILURE_LOCATION
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;


LOAD DATA LOCAL  INFILE 'dft_mdr_test_type.csv' IGNORE
INTO TABLE TEST_TYPES
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;



LOAD DATA LOCAL INFILE 'dft_mdr_fuel_type.csv' IGNORE
INTO TABLE FUEL_TYPES
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;


LOAD DATA LOCAL  INFILE 'dft_mdr_test_outcome.csv' IGNORE
INTO TABLE TEST_OUTCOME
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
;





